[{'name': 'vvid',
  'dataType': <DataType.UUID: 'uuid'>,
  'description': None,
  'indexFilterable': None,
  'indexSearchable': None,
  'nestedProperties': None,
  'skip_vectorization': True,
  'tokenization': None,
  'vectorize_property_name': True},
 {'name': 'section',
  'dataType': <DataType.TEXT: 'text'>,
  'description': None,
  'indexFilterable': None,
  'indexSearchable': None,
  'nestedProperties': None,
  'skip_vectorization': True,
  'tokenization': None,
  'vectorize_property_name': True},
 {'name': 'author',
  'dataType': <DataType.TEXT: 'text'>,
  'description': None,
  'indexFilterable': None,
  'indexSearchable': None,
  'nestedProperties': None,
  'skip_vectorization': True,
  'tokenization': None,
  'vectorize_property_name': True},
 {'name': 'pdf_order',
  'dataType': <DataType.TEXT: 'text'>,
  'description': None,
  'indexFilterable': None,
  'indexSearchable': None,
  'nestedProperties': None,
  'skip_vectorization': True,
  'tokenization': None,
  'vectorize_property_name': True},
 {'name': 'level',
  'dataType': <DataType.TEXT: 'text'>,
  'description': None,
  'indexFilterable': None,
  'indexSearchable': None,
  'nestedProperties': None,
  'skip_vectorization': True,
  'tokenization': None,
  'vectorize_property_name': True},
 {'name': 'title',
  'dataType': <DataType.TEXT: 'text'>,
  'description': None,
  'indexFilterable': None,
  'indexSearchable': None,
  'nestedProperties': None,
  'skip_vectorization': False,
  'tokenization': None,
  'vectorize_property_name': False}]